apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookclub
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/muratozcubukcu/BookClub.git
    targetRevision: master
    path: k8s
    kustomize:
      namePrefix: ""
  destination:
    server: https://kubernetes.default.svc
    namespace: bookclub
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  revisionHistoryLimit: 10
