apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookclub
  labels:
    app: bookclub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookclub
  template:
    metadata:
      labels:
        app: bookclub
    spec:
      containers:
        - name: bookclub
          image: muratozcubukcu/bookclub:latest
          ports:
            - containerPort: 3002
          env:
            - name: PORT
              value: "3002"
          volumeMounts:
            - mountPath: /app/bookclub.db
              name: bookclub-db
              subPath: bookclub.db
      volumes:
        - name: bookclub-db
          emptyDir: {}
